```{r}
setwd("~/Library/CloudStorage/OneDrive-AllenInstitute/Species/Evo-M1-Trait-Data/____Unpublished__ProjectKaskan")
```

```{r}
library(tidyverse)
library(readxl)
library(purrr)
```
## Compare and combine data from Summer Alznati, Jack Gaston and Rachael Robinson's dissertations

# 1 Load all excel files from the directory
```{r}
# Read Rachael's data files

# Define the path to your directory containing the Excel files
path <- "~/Library/CloudStorage/OneDrive-AllenInstitute/Species/Evo-M1-Trait-Data/____Unpublished__ProjectKaskan/Rachael_Robinson_dissertation_file_copies/Brains data for animals"

# List all Excel files in the directory
files <- list.files(path = path, pattern = "\\.xlsx$", full.names = TRUE)

# Read all Excel files into a list of data frames
list_of_dfs <- lapply(files, read_excel)

# Name the list elements after the file names (without the extensions)
names(list_of_dfs) <- gsub("\\.xlsx$", "", basename(files))
names(list_of_dfs)
```
```{r}

```


```{r}
# Combine all data frames into one, if needed (assuming they have the same structure)
combined_df <- bind_rows(list_of_dfs)

# Print the combined data frame (or do further processing)
print(combined_df)


```

