---
title: "EDITING UGLY SPREADSHEETS NOTES"
output: html_document
date: "2023-07-04"
---


# Turn of scientific notation (optional)
```{r}
options(scipen=999)
```

# Set Working Directory. Store with the spreadsheet.
```{r}
setwd("~/Library/CloudStorage/OneDrive-AllenInstitute/Species/Evo M1 Trait Data")
```

# Saved trial from DosSantos et al 2017
```{r}
# Read the spreadsheet
spreadsheet<-read.csv("TESTS NOTES cytoarch GLI cell types.csv")
# Remove unwanted names. Takes names from columns 1-7, adds next to them names from 9-last #assigns new names to original df
names(spreadsheet) = c(names(spreadsheet)[1:7],  names(spreadsheet)[9:length(names(spreadsheet))])
# Delete empty column (you need to run it twice or use two similar functions, for some reason)
spreadsheet[,13]<-NULL
spreadsheet=spreadsheet[,-13]
#spreadsheet[,13]=NULL
# rename columns
colnames(spreadsheet)[colnames(spreadsheet) == "X"] ="Anatomy"
colnames(spreadsheet)[colnames(spreadsheet) == "X.2"] ="delta"
# remove unnecessary character in a specific column
spreadsheet$delta = gsub("x", "", spreadsheet$delta)
# remove unnecessary string in the whole dataset
spreadsheet <- data.frame(sapply(spreadsheet,function(x) gsub("n.a.","",as.character(x))))
spreadsheet <- data.frame(sapply(spreadsheet,function(x) gsub(",","",as.character(x))))
# rename string in columns
colnames(spreadsheet) = gsub("\\b..\\b", "_", colnames(spreadsheet))
# rename string in columns (Genus)
colnames(spreadsheet) = gsub("M_", "Macropus_", colnames(spreadsheet))
# Convert equation string to a number (Steps 1_2)
### Step 1: load tidyverse
library(tidyverse)
## Step 2: look for columns TRUE for 106 or 109. If true, need to multiply equation.   
for (i in 2:length(names(spreadsheet))) {
  spreadsheet$x106=str_detect(spreadsheet[,i], 'x106')
  spreadsheet$x109=str_detect(spreadsheet[,i], 'x109')
  ifelse (spreadsheet$x106 == TRUE, spreadsheet[,i] <- gsub("x106", "", spreadsheet[,i]), spreadsheet[,i])
  ifelse (spreadsheet$x109 == TRUE, spreadsheet[,i] <- gsub("x109", "", spreadsheet[,i]), spreadsheet[,i])
  spreadsheet[,i] <- as.numeric(spreadsheet[,i])
  ifelse (spreadsheet$x106 == TRUE, as.numeric(spreadsheet[,i] <-  spreadsheet[,i]*10^6), spreadsheet[,i])
  ifelse (spreadsheet$x109 == TRUE, as.numeric(spreadsheet[,i] <-  spreadsheet[,i]*10^9), spreadsheet[,i])
}
spreadsheet$x106 = NULL
spreadsheet$x109 = NULL
```

# Saved trial from Caspar et al 2020
```{r}
setwd("/Users/crossmodal/Library/CloudStorage/OneDrive-AllenInstitute/Species/Evo M1 Trait Data/Caspar_etal_2022")

# This extracts most of the table, but the Loxodota africana row at the end is missing!
# Load the tabulizer library and rJava
library(rJava)
library(tabulizer)
library(tabulizerjars)

# Define the PDF file path
pdf_file <- "https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvNzc4NzUvZWxpZmUtNzc4NzUtdjEucGRmP2Nhbm9uaWNhbFVyaT1odHRwczovL2VsaWZlc2NpZW5jZXMub3JnL2FydGljbGVzLzc3ODc1/elife-77875-v1.pdf?_hash=NStjcL9fTlmy3AQDwSiM0YgMVB3UYjO8nDg0UbwN5gM%3D"

# Use extract_tables to get all tables on the specified page
tablessome <- extract_tables(pdf_file, pages = c(6:7))
tablessome

# Specify the column names manually
colnames(table_df) <- c("Species", "Order", "Mass, g", "N, n", "O, n", "N/mg", "O/mg", "O/N", "Source")

# Now, you have the table in 'table_df' with the specified column names
table_df
```

